import type { Feature, Framework } from './types';

export const frameworks: Framework[] = [
  {
    name: 'Next.js',
    ssg: true,
    ssr: false,
    apiRoutes: false,
    isr: false,
    fleekFunctions: true,
    previewDeployments: true,
  },
  {
    name: 'SvelteKit',
    ssg: true,
    ssr: true,
    apiRoutes: false,
    isr: false,
    fleekFunctions: true,
    previewDeployments: true,
  },
  {
    name: 'Astro',
    ssg: true,
    ssr: true,
    apiRoutes: false,
    isr: false,
    fleekFunctions: true,
    previewDeployments: true,
  },
  {
    name: 'Create React App',
    ssg: true,
    ssr: false,
    apiRoutes: false,
    isr: false,
    fleekFunctions: true,
    previewDeployments: true,
  },
  {
    name: 'Vue',
    ssg: true,
    ssr: false,
    apiRoutes: false,
    isr: false,
    fleekFunctions: true,
    previewDeployments: true,
  },
  {
    name: 'Gatsby',
    ssg: true,
    ssr: false,
    apiRoutes: false,
    isr: false,
    fleekFunctions: true,
    previewDeployments: true,
  },
  {
    name: 'Nuxt',
    ssg: true,
    ssr: true,
    apiRoutes: false,
    isr: false,
    fleekFunctions: true,
    previewDeployments: true,
  },
  {
    name: 'Vite',
    ssg: true,
    ssr: false,
    apiRoutes: false,
    isr: false,
    fleekFunctions: true,
    previewDeployments: true,
  },
  {
    name: 'Jekyll',
    ssg: true,
    ssr: false,
    apiRoutes: null,
    isr: null,
    fleekFunctions: true,
    previewDeployments: true,
  },
  {
    name: 'Hugo',
    ssg: true,
    ssr: false,
    apiRoutes: null,
    isr: null,
    fleekFunctions: true,
    previewDeployments: true,
  },
  {
    name: 'Gridsome',
    ssg: true,
    ssr: false,
    apiRoutes: false,
    isr: false,
    fleekFunctions: true,
    previewDeployments: true,
  },
  {
    name: 'Svelte + Sapper',
    ssg: true,
    ssr: true,
    apiRoutes: true,
    isr: false,
    fleekFunctions: true,
    previewDeployments: true,
  },
];

export const features: Feature[] = [
  { key: 'ssg', name: 'SSG' },
  { key: 'ssr', name: 'SSR' },
  { key: 'apiRoutes', name: 'API routes' },
  { key: 'isr', name: 'ISR' },
  { key: 'fleekFunctions', name: 'Fleek Functions' },
  { key: 'previewDeployments', name: 'Preview deployments' },
];
