#!/bin/bash

if [[ -z "$1" || -z "$2" ]]; then
  echo "👹 Oops! Missing argument for the application distribution path ($1) or env vars prefix ($2)..."

  exit 1
fi

targetAppDistPath="$1"
envVarsPrefix="$2"
tempJson="dump.json"
definedOverridesJson="$targetAppDistPath/defined_overrides.json"

echo "🤖 Will attempt to generate $definedOverridesJson..."

if ! doppler secrets download \
  --no-file \
  --format=json > "$tempJson"; then
  echo "👹 Oops! Failed to get doppler's data..."

  exit 1
fi

cat "$tempJson" | jq "with_entries(select(.key | startswith(\"$envVarsPrefix\") ))" > "$definedOverridesJson"

if ! rm "$tempJson"; then
  echo "⚠️Warning: Failed to delete $tempJson"
fi

echo "💡 Created $definedOverridesJson which content is:"
cat "$definedOverridesJson"

echo
echo "✅ Completed defined override setup!"
