#!/bin/bash

TARGET_ENVIRONMENT=${TARGET_ENVIRONMENT:-staging}

prepareDependencyFiles() {
  local targetEnvironment="$1" 
  local targetPublicAppPath="$2"
  local pkgName="$3"
  local pkgDirOutDir="$4"
  local envVarsPrefix="$5"

  echo "🤖 Must prepare Dashboard files for environment $targetEnvironment..."

  if ! scripts/setup-packaged-app \
    "$targetEnvironment" \
    "$targetPublicAppPath" \
    "$pkgName" \
    "$pkgDirOutDir" \
    "$envVarsPrefix"; then
    echo "👹 Oops! Failed to setup the $pkgName files for some reason..."

    exit 1
  fi

  echo "👍 Done preparing $pkgName files!"  
}

prepareDependencyFiles \
  "$TARGET_ENVIRONMENT" \
  "public/dashboard" \
  "@fleek-platform/dashboard" \
  "out" \
  "NEXT_"

prepareDependencyFiles \
  "$TARGET_ENVIRONMENT" \
  "public/agents" \
  "@fleek-platform/agents-ui" \
  "dist" \
  "PUBLIC_"
