#!/bin/bash

if [[ -z "$1" || -z "$2" ]]; then
  echo "👹 Oops! Missing arguments. Have you provided the output path and a base path for the URL?"
  exit 1
fi

output_path="$1"
base_path="$2"
target="$output_path/$base_path/**/*.html"

next_static="_next/static"

# Media path
next_static_media_path_from="$next_static/media"
next_static_media_path_to="$base_path/$next_static/media"

# Chunks path
next_static_chunks_path_from="$next_static/chunks"
next_static_chunks_path_to="$base_path/$next_static/chunks"

find "dist/$base_path" -name "*.html" -type f | while read -r target; do
  if ! sed -i "s|$next_static_media_path_from|$next_static_media_path_to|g" "$target"; then
    echo "👹 Oops! Failed to replace $next_static_media_path_from to $nexT_static_media_path_to for some reason..."
    exit 1
  fi
done

echo "✅ Prefixed $next_static_media_path_from"

find "dist/$base_path" -name "*.html" -type f | while read -r target; do
  if ! sed -i "s|$next_static_chunks_path_from|$next_static_chunks_path_to|g" "$target"; then
    echo "👹 Oops! Failed to replace $next_static_chunks_path_from to $next_static_chunks_path_to for some reason..."
    exit 1
  fi
done

echo "✅ Prefixed $next_static_chunks_path_from"
