#!/bin/bash

ENV="$1"
TARGET_PATH="$2"

if [[ -z "$ENV" || -z "$TARGET_PATH" ]]; then
  echo "👹 Oops! Missing environment variable"
  exit 1
fi

tag="prerelease"
packageName="@fleek-platform/dashboard"
sourcePath="node_modules/@fleek-platform/agents-ui/dist/"
targetPath="$TARGET_PATH"

if [[ "$TARGET_ENVIRONMENT" == 'production' ]]; then
  tag="latest"
fi

if ! npm i --no-save "$packageName@$tag"; then
  echo "👹 Oops! Failed to install the $packageName of tag $tag for some reason..."

  exit 1
fi

if [[ ! -d "$targetPath" ]]; then
  echo "🤖 Should create $targetPath"
  if ! mkdir -p "$targetPath"; then
    echo "👹 Oops! Failed to create directory $targetPath..."
    exit 1
  else
    echo "✅ Successfully created directory $targetPath"
  fi
else
  echo "✅ Directory $targetPath already exists"
fi

cp -r "$sourcePath" "$targetPath"
