import { create } from 'domain';
import { title } from 'process';

export const PERMISSIONS_SECTIONS = {
  project: {
    title: 'Project',
    features: {
      editName: 'Edit name',
      editAvatar: 'Edit avatar',
      deleteProject: 'Delete project',
    },
  },
  storage: {
    title: 'Storage',
    features: {
      editSettings: 'Edit settings',
      uploadContent: 'Upload files/folders',
      editContentName: 'Edit files/folders name',
      deleteContent: 'Delete files/folders',
      getInformation: 'Get information',
      viewContentList: 'View content list',
    },
  },
  site: {
    title: 'Sites',
    features: {
      createSite: 'Create site',
      deploySite: 'Deploy site',
      viewSiteOverview: 'View site overview',
      viewBuildSettings: 'View build settings',
      editBuildSettings: 'Edit build settings',
      viewEnvVariables: 'View environment variables',
      editEnvVariables: 'Edit environment variables',
      viewDeployments: 'View deployments list',
      viewAnalytics: 'View analytics',
      editSiteName: 'Edit site name',
      editSiteSlug: 'Edit site slug',
      editSiteAvatar: 'Edit site avatar',
      purgeCache: 'Purge cache',
      deleteSite: 'Delete site',
      andAndVerifyDomain: 'Add and verify domain',
      changePrimaryDomain: 'Change primary domain',
      deleteDomain: 'Delete domain',
      addAndVerifyEns: 'Add and verify ENS',
      deleteEns: 'Delete ENS',
      addGitIntegration: 'Add Git integration',
      removeGitIntegration: 'Remove Git integration',
    },
  },
  fleekFunctions: {
    title: 'Fleek Functions',
    features: {
      createFunction: 'Create function',
      editSettings: 'Edit settings',
      viewOverview: 'View function overview',
      deployFunction: 'Deploy function',
      deleteFunction: 'Delete function',
    },
  },
  ipns: {
    title: 'IPNS',
    features: {
      create: 'Create a record',
      publish: 'Publish a record',
      delete: 'Delete a record',
      view: 'View records',
    },
  },
  billing: {
    title: 'Billing',
    features: {
      viewBilling: 'View billing',
      editBilling: 'Manage billing',
    },
  },
  applicationCredentials: {
    title: 'Application credentials',
    features: {
      view: 'View',
      create: 'Create',
      edit: 'Edit',
    },
  },
  team: {
    title: 'Team',
    features: {
      invite: 'Invite team members',
      changePermissions: 'Change member permissions',
      assignOwner: 'Assign owner',
      deleteMember: 'Delete member',
    },
  },
};

export const PERMISSIONS_ROLES = {
  owner: {
    features: {
      project: {
        editName: true,
        editAvatar: true,
        deleteProject: true,
      },
      storage: {
        editSettings: true,
        uploadContent: true,
        editContentName: true,
        deleteContent: true,
        getInformation: true,
        viewContentList: true,
      },
      site: {
        createSite: true,
        deploySite: true,
        viewSiteOverview: true,
        viewBuildSettings: true,
        editBuildSettings: true,
        viewEnvVariables: true,
        editEnvVariables: true,
        viewDeployments: true,
        viewAnalytics: true,
        editSiteName: true,
        editSiteSlug: true,
        editSiteAvatar: true,
        purgeCache: true,
        deleteSite: true,
        andAndVerifyDomain: true,
        changePrimaryDomain: true,
        deleteDomain: true,
        addAndVerifyEns: true,
        deleteEns: true,
        addGitIntegration: true,
        removeGitIntegration: true,
      },
      fleekFunctions: {
        createFunction: true,
        editSettings: true,
        viewOverview: true,
        deployFunction: true,
        deleteFunction: true,
      },
      ipns: {
        create: true,
        publish: true,
        delete: true,
        view: true,
      },
      billing: {
        viewBilling: true,
        editBilling: true,
      },
      applicationCredentials: {
        view: true,
        create: true,
        edit: true,
      },
      team: {
        invite: true,
        changePermissions: true,
        assignOwner: true,
        deleteMember: true,
      },
    },
    header: 'Owner',
  },
  admin: {
    features: {
      project: {
        editName: true,
        editAvatar: true,
        deleteProject: false,
      },
      storage: {
        editSettings: true,
        uploadContent: true,
        editContentName: true,
        deleteContent: true,
        getInformation: true,
        viewContentList: true,
      },
      site: {
        createSite: true,
        deploySite: true,
        viewSiteOverview: true,
        viewBuildSettings: true,
        editBuildSettings: true,
        viewEnvVariables: true,
        editEnvVariables: true,
        viewDeployments: true,
        viewAnalytics: true,
        editSiteName: true,
        editSiteSlug: true,
        editSiteAvatar: true,
        purgeCache: true,
        deleteSite: true,
        andAndVerifyDomain: true,
        changePrimaryDomain: true,
        deleteDomain: true,
        addAndVerifyEns: true,
        deleteEns: true,
        addGitIntegration: true,
        removeGitIntegration: true,
      },
      fleekFunctions: {
        createFunction: true,
        editSettings: true,
        viewOverview: true,
        deployFunction: true,
        deleteFunction: true,
      },
      ipns: {
        create: true,
        publish: true,
        delete: true,
        view: true,
      },
      billing: {
        viewBilling: true,
        editBilling: false,
      },
      applicationCredentials: {
        view: true,
        create: true,
        edit: true,
      },
      team: {
        invite: true,
        changePermissions: true,
        assignOwner: false,
        deleteMember: true,
      },
    },
    header: 'Admin',
  },
  member: {
    features: {
      project: {
        editName: true,
        editAvatar: true,
        deleteProject: false,
      },
      storage: {
        editSettings: false,
        uploadContent: true,
        editContentName: true,
        deleteContent: true,
        getInformation: true,
        viewContentList: true,
      },
      site: {
        createSite: true,
        deploySite: true,
        viewSiteOverview: true,
        viewBuildSettings: true,
        editBuildSettings: true,
        viewEnvVariables: true,
        editEnvVariables: true,
        viewDeployments: true,
        viewAnalytics: true,
        editSiteName: true,
        editSiteSlug: true,
        editSiteAvatar: true,
        purgeCache: true,
        deleteSite: false,
        andAndVerifyDomain: true,
        changePrimaryDomain: true,
        deleteDomain: true,
        addAndVerifyEns: true,
        deleteEns: true,
        addGitIntegration: true,
        removeGitIntegration: false,
      },
      fleekFunctions: {
        createFunction: true,
        editSettings: true,
        viewOverview: true,
        deployFunction: true,
        deleteFunction: true,
      },
      ipns: {
        create: true,
        publish: true,
        delete: true,
        view: true,
      },
      billing: {
        viewBilling: false,
        editBilling: false,
      },
      applicationCredentials: {
        view: true,
        create: true,
        edit: true,
      },
      team: {
        invite: false,
        changePermissions: false,
        assignOwner: false,
        deleteMember: false,
      },
    },
    header: 'Member',
  },
  readOnly: {
    features: {
      project: {
        editName: false,
        editAvatar: false,
        deleteProject: false,
      },
      storage: {
        editSettings: false,
        uploadContent: false,
        editContentName: false,
        deleteContent: false,
        getInformation: true,
        viewContentList: true,
      },
      site: {
        createSite: false,
        deploySite: false,
        viewSiteOverview: true,
        viewBuildSettings: true,
        editBuildSettings: false,
        viewEnvVariables: true,
        editEnvVariables: false,
        viewDeployments: true,
        viewAnalytics: true,
        editSiteName: false,
        editSiteSlug: false,
        editSiteAvatar: false,
        purgeCache: false,
        deleteSite: false,
        andAndVerifyDomain: false,
        changePrimaryDomain: false,
        deleteDomain: false,
        addAndVerifyEns: false,
        deleteEns: false,
        addGitIntegration: false,
        removeGitIntegration: false,
      },
      fleekFunctions: {
        createFunction: false,
        editSettings: false,
        viewOverview: true,
        deployFunction: false,
        deleteFunction: false,
      },
      ipns: {
        create: false,
        publish: false,
        delete: false,
        view: true,
      },
      billing: {
        viewBilling: false,
        editBilling: false,
      },
      applicationCredentials: {
        view: true,
        create: false,
        edit: false,
      },
      team: {
        invite: false,
        changePermissions: false,
        assignOwner: false,
        deleteMember: false,
      },
    },
    header: 'Read Only',
  },
};
