name: 🔧 Build (dry-run)

on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  build-dry-run:
    runs-on: ubuntu-22.04
    environment: 'staging'
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      PRIVATE_MEILISEARCH_DOCUMENTS_ADMIN_API_KEY: dry.run
      PUBLIC_MEILISEARCH_DOCUMENTS_CLIENT_API_KEY: dry.run
      PUBLIC_MEILISEARCH_HOST: dry.run
      PUBLIC_SUPPORT_API_HOST: dry.run
      PUBLIC_BEHIIV_API_KEY: dry.run
      PUBLIC_BEHIIV_SUBSCRIBE_URL: 'http://dry.run'
      PUBLIC_BEEHIIV_PROXY_SERVER_URL: 'http://dry.run'
      PUBLIC_GRAPHQL_ENDPOINT: 'http://dry.run'
      PUBLIC_FLEEK_REST_API_URL: 'http://dry.run'
      PUBLIC_DYNAMIC_ENVIRONMENT_ID: 'UNAVAILABLE'
      PUBLIC_UI_APP_URL: 'http://dry.run'
      PUBLIC_PERSONA_GENERATOR_API_URL: 'http://dry.run'
      PUBLIC_APP_HOSTING_URL: 'http://dry.run'
      PUBLIC_APP_AGENTS_URL: 'http://dry.run'
      PUBLIC_OPEN_API_ENDPOINT: 'http://dry.run'
      PUBLIC_CUSTOM_AGENTS_URL: 'http://dry.run'
      PUBLIC_POSTHOG_API_KEY: 'dry.run'
      PUBLIC_POSTHOG_HOST: 'http://dry.run'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Setup Doppler
        run: |
          doppler configure set token "$DOPPLER_TOKEN"

      - name: Env vars health check
        run: |
          if ! doppler run -- printenv | grep -q 'NEXT_PUBLIC_SDK__AUTHENTICATION_URL'; then
            echo "👹 Oops! Missing required environment variable during health check..."
            exit 1           
          fi

          echo "🚑 Doppler envVars seem healthy!"

      - name: Setup dotenv
        run: |
          scripts/setup-ci-dotenv

      - run: npm install --include=optional sharp

      - name: Install
        run: npm ci

      - name: Build site
        run: npm run build
