name: 🫡 Commit checkups (Verification)

on:
 push:
    branches:
      - main
      - develop
 pull_request:

jobs:
 commit-checkups:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        # TODO: Stopped working from
        # https://github.com/fleek-platform/website/actions/runs/13831800908/job/38697801421
        # using npm i as a fallback for now
        # run: bun i
        run: npm install --include=optional sharp

      - name: Commit checks
        run: ./.husky/pre-commit
